In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd
import matplotlib.pylab as plt
import numpy as np
from PIL import Image
import joblib

In [2]:
dataTest = pd.read_csv("test.csv", dtype=float)
dataTest.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

In [3]:
dataTest.count()

pixel0      28000
pixel1      28000
pixel2      28000
pixel3      28000
pixel4      28000
            ...  
pixel779    28000
pixel780    28000
pixel781    28000
pixel782    28000
pixel783    28000
Length: 784, dtype: int64

In [4]:
dataTrain = pd.read_csv("train.csv", dtype=float)
dataTrain.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0    1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1    0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2    1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3    4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4    0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4     0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 785 columns]

In [5]:
dataTrain.count()

label       42000
pixel0      42000
pixel1      42000
pixel2      42000
pixel3      42000
            ...  
pixel779    42000
pixel780    42000
pixel781    42000
pixel782    42000
pixel783    42000
Length: 785, dtype: int64

In [6]:
dataArrayTrain = dataTrain.values
dataArrayTest = dataTest.values

In [7]:
dataArrayTrain[:,1:] = dataArrayTrain[:,1:] / 255
dataArrayTest[:,1:] = dataArrayTest[:,1:] / 255

In [8]:
mlp = MLPClassifier(hidden_layer_sizes=(20,), activation='logistic', solver='sgd', verbose=True, random_state=1, max_iter=600, alpha=0.001, learning_rate_init=0.01)

In [9]:
mlp.fit(dataArrayTrain[:,1:], dataArrayTrain[:,0])

Iteration 1, loss = 1.96677550
Iteration 2, loss = 1.18356554
Iteration 3, loss = 0.80875853
Iteration 4, loss = 0.63399630
Iteration 5, loss = 0.53349931
Iteration 6, loss = 0.46984798
Iteration 7, loss = 0.42696765
Iteration 8, loss = 0.39616599
Iteration 9, loss = 0.37310383
Iteration 10, loss = 0.35497637
Iteration 11, loss = 0.34013051
Iteration 12, loss = 0.32770771
Iteration 13, loss = 0.31689234
Iteration 14, loss = 0.30768694
Iteration 15, loss = 0.29941328
Iteration 16, loss = 0.29198513
Iteration 17, loss = 0.28533284
Iteration 18, loss = 0.27909278
Iteration 19, loss = 0.27348103
Iteration 20, loss = 0.26838198
Iteration 21, loss = 0.26354362
Iteration 22, loss = 0.25903094
Iteration 23, loss = 0.25468710
Iteration 24, loss = 0.25072193
Iteration 25, loss = 0.24697511
Iteration 26, loss = 0.24328707
Iteration 27, loss = 0.23984372
Iteration 28, loss = 0.23652218
Iteration 29, loss = 0.23351252
Iteration 30, loss = 0.23050337
Iteration 31, loss = 0.22774175
Iteration 32, los

D:\program\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (600) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='logistic', alpha=0.001, hidden_layer_sizes=(20,),
              learning_rate_init=0.01, max_iter=600, random_state=1,
              solver='sgd', verbose=True)

In [10]:
print("Training set score: %f" % mlp.score(dataArrayTrain[:,1:], dataArrayTrain[:,0]))
#print("Test set score: %f" % mlp.score(dataArrayTest[:,1:], dataArrayTest[:,0]))

Training set score: 0.987976


In [ ]:
estimator = MLPClassifier(activation='logistic',solver='sgd', verbose=True)
parameters = {
    'learning_rate_init':[0.0001, 0.001, 0.01, 0.1, 1],
    'alpha':[0.0001, 0.001, 0.01, 0.1, 1],
    'hidden_layer_sizes':[(20,), (5,5,5), (30,), (10,10), (1,2,3,4)],
    'max_iter':[100, 500, 600, 700, 1000],
}

clf = GridSearchCV(estimator, parameters, cv = 4, n_jobs = -1, verbose=3)

In [12]:
clf.fit(dataArrayTrain[:,1:], dataArrayTrain[:,0])

Fitting 4 folds for each of 625 candidates, totalling 2500 fits
Iteration 1, loss = 0.74016709
Iteration 2, loss = 0.30455347
Iteration 3, loss = 0.25607961
Iteration 4, loss = 0.22856319
Iteration 5, loss = 0.20817473
Iteration 6, loss = 0.19327859
Iteration 7, loss = 0.18136963
Iteration 8, loss = 0.17191459
Iteration 9, loss = 0.16406181
Iteration 10, loss = 0.15640015
Iteration 11, loss = 0.15079926
Iteration 12, loss = 0.14530301
Iteration 13, loss = 0.14080119
Iteration 14, loss = 0.13703398
Iteration 15, loss = 0.13339487
Iteration 16, loss = 0.13020657
Iteration 17, loss = 0.12717016
Iteration 18, loss = 0.12458776
Iteration 19, loss = 0.12220700
Iteration 20, loss = 0.12020020
Iteration 21, loss = 0.11805173
Iteration 22, loss = 0.11626223
Iteration 23, loss = 0.11421159
Iteration 24, loss = 0.11303236
Iteration 25, loss = 0.11145023
Iteration 26, loss = 0.11062905
Iteration 27, loss = 0.10870540
Iteration 28, loss = 0.10810120
Iteration 29, loss = 0.10658187
Iteration 30, los

GridSearchCV(cv=4,
             estimator=MLPClassifier(activation='logistic', solver='sgd',
                                     verbose=True),
             n_jobs=-1,
             param_grid={'alpha': [0.0001, 0.001, 0.01, 0.1, 1],
                         'hidden_layer_sizes': [(20,), (5, 5, 5), (30,),
                                                (10, 10), (1, 2, 3, 4)],
                         'learning_rate_init': [0.0001, 0.001, 0.01, 0.1, 1],
                         'max_iter': [100, 500, 600, 700, 1000]},
             verbose=3)

In [13]:
print("Training set score: %f" % clf.score(dataArrayTrain[:,1:], dataArrayTrain[:,0]))
#print("Test set score: %f" % clf.score(dataArrayTest[:,1:], dataArrayTest[:,0]))

Training set score: 0.995738


In [14]:
clf.best_params_

{'alpha': 0.01,
 'hidden_layer_sizes': (30,),
 'learning_rate_init': 0.1,
 'max_iter': 600}

In [15]:
img = np.asarray(Image.open('1.png').convert('L'))
img = img.reshape(1,784) / 255
img

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [16]:
img = np.asarray(Image.open('1.png').convert('L'))
t = mlp.predict(img.reshape(1,784) / 255)
t

array([5.])

In [17]:
img = np.asarray(Image.open('1.png').convert('L'))
clf.predict(img.reshape(1,784) / 255)

array([4.])

In [18]:
dataArrayTest[1:2,1:]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [19]:
mlp.predict(dataArrayTest[2:3,:])

array([9.])

In [20]:
clf.predict(dataArrayTest[2:3,:])

array([9.])

In [21]:
joblib.dump(clf, "clf_model.pkl")

['clf_model.pkl']

In [22]:
joblib.dump(mlp, "mlp_model.pkl")

['mlp_model.pkl']

In [ ]:
plt.imshow(np.reshape(dataArrayTest[2:3,:], (28, 28)), cmap=plt.cm.binary)
plt.show()

In [9]:
dataTestNew = pd.read_csv("mnist_test.csv", dtype=float)
dataTestNew.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0    7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
1    2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
2    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
4    4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 785 columns]

In [13]:
dataArrayTestNew = dataTestNew.values

In [14]:
q = joblib.load("clf_model.pkl",  'r')

In [25]:
img = np.asarray(Image.open('1.png').convert('L'))
q.predict(img.reshape(1,784) / 255)

array([5.])

In [15]:
#print("Test set score: %f" % q.score(test[:,1, test[:,0]))
print("Test set score: %f" % q.score(dataArrayTestNew[:,1:], dataArrayTestNew[:,0]))

Test set score: 0.941300
