In [11]:
# Задание 1. Подключите библиотеку NumPy

import numpy as np

In [8]:
# Задание 2. Исправить ошибку

a = np.array([4, 5, 4])
c = np.array([1, 2])
try:
    d = a + c
    print(d)
except Exception as e:
    print("Error:")
    print(e)

Error:
operands could not be broadcast together with shapes (3,) (2,) 


In [ ]:
# Задание 3. Написать код для умножения вектора на скалярное значение

a = np.array([1, 2, 3, 4])
b = #...
print(f"b = 5 * a : {b}")

Формуля для нахождения скаляроного произведения:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$


In [12]:
# Задание 4. Допишите функцию, которая находит скаларное произведение двух векторов

def dot_product_of_vectors(a, b): 
    x=0
    for i in range(a.shape[0]):
        # ...
    return x

In [13]:
# Тест для задания 4
a = np.array([-5, 4, 2, 4])
b = np.array([1, 8, 3, 2])
print(f"dot_product_of_vectors(a, b) = {dot_product_of_vectors(a, b)}")

dot_product_of_vectors(a, b) = 24


In [15]:
# Задание 5. Выполните скалярное умножение векторов, используя стандартную функцию "dot". Чем является результат функции?
a = np.array([-5, 4, 2, 4])
b = np.array([1, 8, 3, 2])
c = # ... Код для скалярное умножения вектора a на вектор b
print(f"product = {c}") 
c = # ... Код для скалярного умножения b на a
print(f"product = {c}")

product = 41
product = 41


In [19]:
# Задание 6. Посмотреть на пример работы собственной функции dot_product_of_vectors и функцию dot из библиотеки NumPy. Сделать выводы.

import time

np.random.seed(1)
a = np.random.rand(10000000)  
b = np.random.rand(10000000)

tic = time.time()  
c = np.dot(a, b)
toc = time.time()  

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Time : {1000*(toc-tic):.4f} ms \n")

tic = time.time()  
c = dot_product_of_vectors(a,b)
toc = time.time()  

print(f"dot_product_of_vectors(a, b) =  {c:.4f}")
print(f"Time : {1000*(toc-tic):.4f} ms ")

del(a);del(b)  

np.dot(a, b) =  2501072.5817
Time : 18.3415 ms 

dot_product_of_vectors(a, b) =  2501072.5817
Time : 4979.1291 ms 


In [22]:
# Задание 7. Вывести размеры контейнеров. Вставить код вместо многоточий

X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X has shape {...}")
print(f"X[1] has shape {...}")
print(f"w has shape {...}")
print(f"c has shape {...}")

X has shape Ellipsis
X[1] has shape Ellipsis
w has shape Ellipsis
c has shape Ellipsis


In [25]:
# Задание 8. Создать массивы...

# Массив 1Х5 , заполненный нулями
# Массив 2Х1 , заполненный нулями
# Массив 1Х1 , с рандомным значением

# Вывести размеры всех массивов в удобном формате, например: print(f"a shape = {a.shape}, a = {a}") 


a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.77390955]]


In [26]:
# Задание 9. Создать массивы и заполнить их произвольными числами...

# Массив 1Х3
# Массив 3Х3
# Массив 3Х3Х3

# Вывести размеры всех массивов в удобном формате

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [29]:
# Задание 10. 

a = np.arange(6).reshape(-1, 2)   # Как можно было записать иначе? 
print(f"a.shape: {a.shape}, \na= {a}")

# Вывести элемент матрицы, который находится в последней строке и первом столбце и посмотреть тип с помощью функции type()

# Вывести вторую по счету строку матрицы и посмотреть тип с помощью функции type()


a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


In [32]:
# Задание 10. Рассмотреть примеры

a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}\n\n")
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array\n\n")
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array\n\n")
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape,"\n\n")
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array\n\n")
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array\n\n")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array


a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array


a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10) 


a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array


a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array




In [39]:
# Задание 11.

a = np.arange(1,31).reshape(-1, 10)

# Вывести предпоследний столбец матрицы
# Вывести предпоследнюю чтроку матрицы
# Вывести середину матрицы (числа 12, 13, 14, 15, 16, 17, 18, 19)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])